#
# development configuration
spring:
   config:
      activate:
         on-profile: development

   devtools:
      livereload:
         enabled: true

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://potential-mariadb.c4jotwudvoiz.ap-northeast-2.rds.amazonaws.com:3306/retirement
      username: potential03
      password: potential03
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         
   security:
      oauth2:
         resourceserver:
           jwt:
              issuer-uri: http://potential-loadbalancer-171085408.ap-northeast-1.elb.amazonaws.com:5555/realms/potential
              jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs   

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: DEBUG

eureka:
   instance:
      preferIpAddress: true
      ip-address: 18.182.25.37
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://potential-loadbalancer-171085408.ap-northeast-1.elb.amazonaws.com:8761/eureka
   