# configuration: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://potential-mariadb.c4jotwudvoiz.ap-northeast-2.rds.amazonaws.com:3306/retirement
      username: potential03
      password: potential03
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         
   security:
      oauth2:
         resourceserver:
           jwt:
              issuer-uri: https://keycloak.po-tential.site/realms/potential
              jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs         

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: INFO
      com:
         poscodx:
            msa:
               service:
                  guestbook:
                     exception: ERROR
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: https://eureka.po-tential.site/eureka